table:
  name: job_application
  schema: public
object_relationships:
  - name: candidate
    using:
      foreign_key_constraint_on: candidateId
  - name: employee
    using:
      foreign_key_constraint_on: reviewer_id
  - name: job_position
    using:
      foreign_key_constraint_on: positionId
array_relationships:
  - name: interviews
    using:
      foreign_key_constraint_on:
        column: applicationId
        table:
          name: interview
          schema: public
insert_permissions:
  - role: candidate
    permission:
      check: {}
      columns:
        - candidateId
        - candidate_email
        - candidate_name
        - cover_letter
        - expected_salary
        - positionId
        - referral_source
        - resume_url
    comment: ""
select_permissions:
  - role: candidate
    permission:
      columns:
        - has_reviewed
        - candidate_email
        - candidate_name
        - cover_letter
        - referral_source
        - resume_url
        - expected_salary
        - applied_at
        - status
        - candidateId
        - id
        - positionId
        - reviewer_id
      filter:
        candidateId:
          _eq: X-Hasura-User-Id
    comment: ""
  - role: HRING_MANAGER
    permission:
      columns:
        - has_reviewed
        - candidate_email
        - candidate_name
        - cover_letter
        - referral_source
        - resume_url
        - expected_salary
        - applied_at
        - status
        - candidateId
        - id
        - positionId
        - reviewer_id
      filter: {}
    comment: ""
  - role: HR
    permission:
      columns:
        - has_reviewed
        - candidate_email
        - candidate_name
        - cover_letter
        - referral_source
        - resume_url
        - expected_salary
        - applied_at
        - status
        - candidateId
        - id
        - positionId
        - reviewer_id
      filter: {}
    comment: ""
  - role: INTERVIEWER
    permission:
      columns:
        - applied_at
        - candidateId
        - candidate_email
        - candidate_name
        - cover_letter
        - expected_salary
        - has_reviewed
        - positionId
        - referral_source
        - resume_url
        - reviewer_id
        - status
      filter: {}
    comment: ""
  - role: RECRUITER
    permission:
      columns:
        - has_reviewed
        - candidate_email
        - candidate_name
        - cover_letter
        - referral_source
        - resume_url
        - expected_salary
        - applied_at
        - status
        - candidateId
        - id
        - positionId
        - reviewer_id
      filter: {}
    comment: ""
update_permissions:
  - role: HIRING_MANAGER
    permission:
      columns:
        - status
      filter: {}
      check: null
    comment: ""
  - role: HR
    permission:
      columns:
        - status
      filter: {}
      check: null
    comment: ""
delete_permissions:
  - role: candidate
    permission:
      filter: {}
    comment: ""
  - role: HIRING_MANAGER
    permission:
      filter: {}
    comment: ""
  - role: HR
    permission:
      filter: {}
    comment: ""
  - role: RECRUITER
    permission:
      filter: {}
    comment: ""
